/*
 * MainGui.java
 *
 * Created on 12 novembre 2008, 10.00
 */

package lpr.minikazaa.minikazaaclient;

import lpr.minikazaa.GUI.SearchPanel;
import lpr.minikazaa.util.Constants;

/**
 *
 * @author  giovine
 */
public class MainGui extends javax.swing.JFrame {
    private NodeConfig my_conf;
    /** Creates new form MainGui */
    public MainGui(NodeConfig conf) {
        
        this.my_conf = conf;
        initComponents();
        
        
               
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        connect_bt = new javax.swing.JButton();
        disconnect_bt = new javax.swing.JButton();
        search_bt = new javax.swing.JButton();
        transfer_bt = new javax.swing.JButton();
        shared_bt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        connection_status = new javax.swing.JLabel();
        main_tab = new javax.swing.JTabbedPane();
        main_menu_bar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(Constants.SAVE_EVERYTHING);
        setTitle("MiNi-KaZaA");

        jToolBar1.setRollover(true);

        connect_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/connections_icon.png"))); // NOI18N
        connect_bt.setText("Connect");
        connect_bt.setFocusable(false);
        connect_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connect_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(connect_bt);

        disconnect_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/discconnections_icon.png"))); // NOI18N
        disconnect_bt.setText("Disconnect");
        disconnect_bt.setFocusable(false);
        disconnect_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disconnect_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(disconnect_bt);

        search_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/search_icon.png"))); // NOI18N
        search_bt.setText("Search");
        search_bt.setFocusable(false);
        search_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btActionPerformed(evt);
            }
        });
        jToolBar1.add(search_bt);

        transfer_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/transfer_icon.png"))); // NOI18N
        transfer_bt.setText("File Transfer");
        transfer_bt.setFocusable(false);
        transfer_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transfer_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transfer_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_btActionPerformed(evt);
            }
        });
        jToolBar1.add(transfer_bt);

        shared_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/shared_files_icon.png"))); // NOI18N
        shared_bt.setText("Shared Files");
        shared_bt.setFocusable(false);
        shared_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shared_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(shared_bt);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/network_icon.png"))); // NOI18N
        jButton2.setText("Net Monitor");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        connection_status.setText("jLabel2");

        jMenu3.setText("File");
        main_menu_bar1.add(jMenu3);

        jMenu4.setText("Edit");
        main_menu_bar1.add(jMenu4);

        setJMenuBar(main_menu_bar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addComponent(connection_status)
                .addContainerGap())
            .addComponent(main_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connection_status))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btActionPerformed
    this.main_tab.addTab("Search", new SearchPanel());
}//GEN-LAST:event_search_btActionPerformed

private void transfer_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_btActionPerformed
    
}//GEN-LAST:event_transfer_btActionPerformed

    
    @Override
    public void setDefaultCloseOperation(int operation){
        switch(operation){
            case Constants.SAVE_EVERYTHING: this.myDefaultCloseOperation();break;
            default: super.setDefaultCloseOperation(operation);break;
                
        }
    } 
    
    private void myDefaultCloseOperation(){
        //Operation to do on close.
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_bt;
    private javax.swing.JLabel connection_status;
    private javax.swing.JButton disconnect_bt;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar main_menu_bar1;
    private javax.swing.JTabbedPane main_tab;
    private javax.swing.JButton search_bt;
    private javax.swing.JButton shared_bt;
    private javax.swing.JButton transfer_bt;
    // End of variables declaration//GEN-END:variables

}
