/*
 * MainGui.java
 *
 * Created on 12 novembre 2008, 10.00
 */
package lpr.minikazaa.minikazaaclient;

import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.awt.event.WindowListener;
import java.awt.event.WindowStateListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import lpr.minikazaa.GUI.SearchPanel;
import lpr.minikazaa.GUI.SharedFilesPanel;
import lpr.minikazaa.GUI.TransferPanel;
import lpr.minikazaa.minikazaaclient.ordinarynode.OrdinarynodeFiles;
import lpr.minikazaa.util.FileUtil;

/**
 *
 * @author Andrea Di Grazia, Massimiliano Giovine
 */
public class MainGui extends javax.swing.JFrame implements WindowListener, WindowFocusListener, WindowStateListener {

    private NodeConfig my_conf;
    private OrdinarynodeFiles my_files;

    /** Creates new form MainGui */
    public MainGui(NodeConfig conf, OrdinarynodeFiles file_list) {
        this.my_files = file_list;
        this.my_conf = conf;
        initComponents();

        if (!this.my_conf.getIsSN()) {
            //Unable to watch net monitor
            this.net_bt.setEnabled(false);
        }

        //Listeners to our window
        addWindowListener(this);
        addWindowFocusListener(this);
        addWindowStateListener(this);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        connect_bt = new javax.swing.JButton();
        disconnect_bt = new javax.swing.JButton();
        search_bt = new javax.swing.JButton();
        transfer_bt = new javax.swing.JButton();
        shared_bt = new javax.swing.JButton();
        net_bt = new javax.swing.JButton();
        close_tab_bt = new javax.swing.JButton();
        shut_down_bt = new javax.swing.JButton();
        connection_status = new javax.swing.JLabel();
        main_tab = new javax.swing.JTabbedPane();
        main_menu_bar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setTitle("MiNi-KaZaA");
        setIconImage(new ImageIcon(getClass().getResource("/lpr/minikazaa/icons/mini_kazaa_main_icon.png")).getImage());

        jToolBar1.setRollover(true);

        connect_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/connections_icon.png"))); // NOI18N
        connect_bt.setText("Connect");
        connect_bt.setFocusable(false);
        connect_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connect_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(connect_bt);

        disconnect_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/discconnections_icon.png"))); // NOI18N
        disconnect_bt.setText("Disconnect");
        disconnect_bt.setFocusable(false);
        disconnect_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disconnect_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(disconnect_bt);

        search_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/search_icon.png"))); // NOI18N
        search_bt.setText("Search");
        search_bt.setFocusable(false);
        search_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btActionPerformed(evt);
            }
        });
        jToolBar1.add(search_bt);

        transfer_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/transfer_icon.png"))); // NOI18N
        transfer_bt.setText("File Transfer");
        transfer_bt.setFocusable(false);
        transfer_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transfer_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transfer_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_btActionPerformed(evt);
            }
        });
        jToolBar1.add(transfer_bt);

        shared_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/shared_files_icon.png"))); // NOI18N
        shared_bt.setText("Shared Files");
        shared_bt.setFocusable(false);
        shared_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shared_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shared_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shared_btActionPerformed(evt);
            }
        });
        jToolBar1.add(shared_bt);

        net_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/network_icon.png"))); // NOI18N
        net_bt.setText("Net Monitor");
        net_bt.setFocusable(false);
        net_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        net_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(net_bt);

        close_tab_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/close_tab_icon.png"))); // NOI18N
        close_tab_bt.setText("Close Tab");
        close_tab_bt.setFocusable(false);
        close_tab_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        close_tab_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        close_tab_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_tab_btActionPerformed(evt);
            }
        });
        jToolBar1.add(close_tab_bt);

        shut_down_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/shut_down_icon.png"))); // NOI18N
        shut_down_bt.setText("Shut Down");
        shut_down_bt.setFocusable(false);
        shut_down_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shut_down_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(shut_down_bt);

        connection_status.setText("jLabel2");

        jMenu3.setText("File");
        main_menu_bar1.add(jMenu3);

        jMenu4.setText("Edit");
        main_menu_bar1.add(jMenu4);

        setJMenuBar(main_menu_bar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(724, Short.MAX_VALUE)
                .addComponent(connection_status)
                .addContainerGap())
            .addComponent(main_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connection_status))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void search_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btActionPerformed
    ImageIcon icon = new ImageIcon(getClass().getResource("/lpr/minikazaa/icons/mini_search_icon.png"));
    this.main_tab.addTab("Search", icon, new SearchPanel(), "Search files in the network.");
}//GEN-LAST:event_search_btActionPerformed

private void transfer_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_btActionPerformed
    int index = 0;

    try {
        String s = null;
        while (true) {
            s = this.main_tab.getTitleAt(index);

            if (s.equals("Transfer")) {
                return;
            }
            index++;
        }
    } catch (IndexOutOfBoundsException ex) {

        ImageIcon icon = new ImageIcon(getClass().getResource("/lpr/minikazaa/icons/mini_transfer_icon.png"));
        this.main_tab.addTab("Transfer", icon, new TransferPanel(), "Monitor your transfert.");

        return;
    }
}//GEN-LAST:event_transfer_btActionPerformed

private void close_tab_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_tab_btActionPerformed

    int tab_to_remove = this.main_tab.getSelectedIndex();
    this.main_tab.remove(tab_to_remove);
}//GEN-LAST:event_close_tab_btActionPerformed

private void shared_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shared_btActionPerformed
    //Call a new panel to view, add or remove files to share with other users.

    int index = 0;

    try {
        String s = null;
        while (true) {
            s = this.main_tab.getTitleAt(index);

            if (s.equals("Shared Files")) {
                return;
            }
            index++;
        }
    } catch (IndexOutOfBoundsException ex) {

        SharedFilesPanel shared_files_panel = new SharedFilesPanel(this.my_files);
        ImageIcon icon = new ImageIcon(getClass().getResource("/lpr/minikazaa/icons/mini_shared_files_icon.png"));
        this.main_tab.addTab("Shared Files", icon, shared_files_panel, "Manage your sharings.");

        return;
    }

}//GEN-LAST:event_shared_btActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_tab_bt;
    private javax.swing.JButton connect_bt;
    private javax.swing.JLabel connection_status;
    private javax.swing.JButton disconnect_bt;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar main_menu_bar1;
    private javax.swing.JTabbedPane main_tab;
    private javax.swing.JButton net_bt;
    private javax.swing.JButton search_bt;
    private javax.swing.JButton shared_bt;
    private javax.swing.JButton shut_down_bt;
    private javax.swing.JButton transfer_bt;
    // End of variables declaration//GEN-END:variables

    public void windowOpened(WindowEvent arg0) {
        //Do nothing
    }

    public void windowClosed(WindowEvent arg0) {
        //Do nothing.
    }

    public void windowIconified(WindowEvent arg0) {
        //Do nothing
    }

    public void windowDeiconified(WindowEvent arg0) {
        //Do nothing
    }

    public void windowActivated(WindowEvent arg0) {
        //Do nothing
    }

    public void windowDeactivated(WindowEvent arg0) {
        //Do nothing
    }

    /**
     *
     *
     * @param e event that handle windows closing operation.
     */
    public void windowClosing(WindowEvent e) {
        System.out.println("Everything saved.");
        FileUtil.saveMySharedFiles(my_files);
        System.exit(0);
    }

    public void windowGainedFocus(WindowEvent arg0) {
        //Do nothing
    }

    public void windowLostFocus(WindowEvent arg0) {
        //Do nothing
    }

    public void windowStateChanged(WindowEvent arg0) {
        //Do nothing
    }
}
