/*
 * MainGui.java
 *
 * Created on 12 novembre 2008, 10.00
 */

package lpr.minikazaa.minikazaaclient;

import lpr.minikazaa.util.Constants;

/**
 *
 * @author  giovine
 */
public class MainGui extends javax.swing.JFrame {
    private NodeConfig my_conf;
    /** Creates new form MainGui */
    public MainGui(NodeConfig conf) {
        this.my_conf = conf;
        initComponents();
        this.search_tf.selectAll();
               
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_menu_bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        connect_bt = new javax.swing.JButton();
        disconnect_bt = new javax.swing.JButton();
        search_bt = new javax.swing.JButton();
        transfer_bt = new javax.swing.JButton();
        shared_bt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        search_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        start_search_bt = new javax.swing.JButton();
        stop_search_bt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        connection_status = new javax.swing.JLabel();
        main_menu_bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(Constants.SAVE_EVERYTHING);

        jMenu1.setText("File");
        main_menu_bar.add(jMenu1);

        jMenu2.setText("Edit");
        main_menu_bar.add(jMenu2);

        setJMenuBar(main_menu_bar);

        jToolBar1.setRollover(true);

        connect_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/connections_icon.png"))); // NOI18N
        connect_bt.setText("Connect");
        connect_bt.setFocusable(false);
        connect_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connect_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(connect_bt);

        disconnect_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/discconnections_icon.png"))); // NOI18N
        disconnect_bt.setText("Disconnect");
        disconnect_bt.setFocusable(false);
        disconnect_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        disconnect_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(disconnect_bt);

        search_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/search_icon.png"))); // NOI18N
        search_bt.setText("Search");
        search_bt.setFocusable(false);
        search_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(search_bt);

        transfer_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/transfer_icon.png"))); // NOI18N
        transfer_bt.setText("File Transfer");
        transfer_bt.setFocusable(false);
        transfer_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transfer_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(transfer_bt);

        shared_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/shared_files_icon.png"))); // NOI18N
        shared_bt.setText("Shared Files");
        shared_bt.setFocusable(false);
        shared_bt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shared_bt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(shared_bt);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/network_icon.png"))); // NOI18N
        jButton2.setText("Net Monitor");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        search_tf.setText("...type research parameters here...");

        jLabel1.setText("Search:");

        start_search_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/mini_connect_icon.png"))); // NOI18N

        stop_search_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/mini_stop_icon.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panelLayout.createSequentialGroup()
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, search_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start_search_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop_search_bt)))
                .addContainerGap())
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(start_search_bt)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stop_search_bt))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        connection_status.setText("jLabel2");

        jMenu1.setText("File");
        main_menu_bar.add(jMenu1);

        jMenu2.setText("Edit");
        main_menu_bar.add(jMenu2);

        setJMenuBar(main_menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addComponent(search_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .addComponent(connection_status)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(connection_status))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public void setDefaultCloseOperation(int operation){
        switch(operation){
            case Constants.SAVE_EVERYTHING: this.myDefaultCloseOperation();break;
            default: super.setDefaultCloseOperation(operation);break;
                
        }
    } 
    
    private void myDefaultCloseOperation(){
        //Operation to do on close.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_bt;
    private javax.swing.JLabel connection_status;
    private javax.swing.JButton disconnect_bt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar main_menu_bar;
    private javax.swing.JButton search_bt;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTextField search_tf;
    private javax.swing.JButton shared_bt;
    private javax.swing.JButton start_search_bt;
    private javax.swing.JButton stop_search_bt;
    private javax.swing.JButton transfer_bt;
    // End of variables declaration//GEN-END:variables

}
