/*
 * SupernodeMainGui.java
 *
 * Created on 18 settembre 2008, 11.37
 */

package lpr.minikazaa.minikazaaclient.supernode;

import javax.swing.table.DefaultTableModel;
import lpr.minikazaa.bootstrap.NodeInfo;
import lpr.minikazaa.minikazaaclient.NodeConfig;
import lpr.minikazaa.minikazaaclient.SupernodeList;

/**
 *
 * @author  andrea
 */
public class SupernodeMainGui extends javax.swing.JFrame {
    
    NodeConfig my_conf;
    SupernodeList my_list;

    /** Creates new form SupernodeMainGui */
    public SupernodeMainGui(NodeConfig conf, SupernodeList list) {
        this.my_conf = conf;
        this.my_list = list;
        
        initComponents();
        
        this.my_address_tf.setText(my_conf.getMyAddress());
    }
    
    public void addSuperNodeTableRow(NodeInfo n){
        DefaultTableModel def_sn_table = (DefaultTableModel) this.Sn_connection_table.getModel();
        String [] a = new String[1];
        a[0] = n.toTable();
        def_sn_table.addRow(a);
        this.Sn_connection_table.setModel(def_sn_table);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        my_address_tf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Sn_connection_table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        On_connection_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        connect_item = new javax.swing.JMenuItem();
        disconnect_item = new javax.swing.JMenuItem();
        close_item = new javax.swing.JMenuItem();
        edit_menu = new javax.swing.JMenu();
        add_sn_item = new javax.swing.JMenuItem();
        remove_sn_item = new javax.swing.JMenuItem();
        add_on_item = new javax.swing.JMenuItem();
        remove_on_item = new javax.swing.JMenuItem();
        configure_item = new javax.swing.JMenuItem();
        question_menu = new javax.swing.JMenu();
        help_item = new javax.swing.JMenuItem();
        italian_help_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SUPERNODE Control Panel");

        jLabel2.setText("IP address:");

        my_address_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                my_address_tfActionPerformed(evt);
            }
        });

        Sn_connection_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "IP address", "File", "O.N. connected"
            }
        ));
        jScrollPane1.setViewportView(Sn_connection_table);

        jLabel3.setText("SuperNode connection:");

        jLabel4.setText("OrdinaryNode connection:");

        On_connection_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "IP addres", "File", "Distance of me"
            }
        ));
        jScrollPane2.setViewportView(On_connection_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connection zone", jPanel1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("File list ", jPanel2);

        file_menu.setText("File");

        connect_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        connect_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/connect_icon.png"))); // NOI18N
        connect_item.setText("Connect");
        connect_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_itemActionPerformed(evt);
            }
        });
        file_menu.add(connect_item);

        disconnect_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        disconnect_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/disconnect_icon.png"))); // NOI18N
        disconnect_item.setText("Disconnect");
        disconnect_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_itemActionPerformed(evt);
            }
        });
        file_menu.add(disconnect_item);

        close_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        close_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/close_icon.png"))); // NOI18N
        close_item.setText("Close");
        close_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_itemActionPerformed(evt);
            }
        });
        file_menu.add(close_item);

        jMenuBar1.add(file_menu);

        edit_menu.setText("Edit");

        add_sn_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/add_icon.png"))); // NOI18N
        add_sn_item.setText("Add S.N");
        add_sn_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_sn_itemActionPerformed(evt);
            }
        });
        edit_menu.add(add_sn_item);

        remove_sn_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/remove_icon.png"))); // NOI18N
        remove_sn_item.setText("Remove S.N");
        remove_sn_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_sn_itemActionPerformed(evt);
            }
        });
        edit_menu.add(remove_sn_item);

        add_on_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/add_icon.png"))); // NOI18N
        add_on_item.setText("Add O.N.");
        add_on_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_on_itemActionPerformed(evt);
            }
        });
        edit_menu.add(add_on_item);

        remove_on_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/remove_icon.png"))); // NOI18N
        remove_on_item.setText("Remove O.N.");
        remove_on_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_on_itemActionPerformed(evt);
            }
        });
        edit_menu.add(remove_on_item);

        configure_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/config_icon.png"))); // NOI18N
        configure_item.setText("Configure");
        configure_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configure_itemActionPerformed(evt);
            }
        });
        edit_menu.add(configure_item);

        jMenuBar1.add(edit_menu);

        question_menu.setText("?");

        help_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/about_icon.png"))); // NOI18N
        help_item.setText("Help");
        question_menu.add(help_item);

        italian_help_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpr/minikazaa/icons/italian_about_icon.png"))); // NOI18N
        italian_help_item.setText("Italian Help");
        italian_help_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italian_help_itemActionPerformed(evt);
            }
        });
        question_menu.add(italian_help_item);

        jMenuBar1.add(question_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(my_address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(my_address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void my_address_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_my_address_tfActionPerformed
// RILEVAMENTO ED INSERIMENTO DELL INDIRIZZO IP DEL SUPERNODO....
}//GEN-LAST:event_my_address_tfActionPerformed

private void italian_help_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italian_help_itemActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_italian_help_itemActionPerformed

private void connect_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_itemActionPerformed
// CONNETTE ALLA RETE MINIKAZAAAAAAA....
}//GEN-LAST:event_connect_itemActionPerformed

private void disconnect_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnect_itemActionPerformed
// DISCONNETTI ALLA RETE MINIKAZAAAAA....
}//GEN-LAST:event_disconnect_itemActionPerformed

private void close_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_itemActionPerformed
// CHIUDI APPLICAZIONE ...
}//GEN-LAST:event_close_itemActionPerformed

private void add_sn_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_sn_itemActionPerformed
// AGGIUNGI UNA SN CONNECTION...
}//GEN-LAST:event_add_sn_itemActionPerformed

private void remove_sn_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_sn_itemActionPerformed
// RIMUOVI UNA SN CONNECTION....
}//GEN-LAST:event_remove_sn_itemActionPerformed

private void add_on_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_on_itemActionPerformed
// AGGIUNGI UNA ON CONNECTION...
}//GEN-LAST:event_add_on_itemActionPerformed

private void remove_on_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_on_itemActionPerformed
// RIMUOVI UNA ON CONNECTION...
}//GEN-LAST:event_remove_on_itemActionPerformed

private void configure_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configure_itemActionPerformed
// APRIRE L' INTEFACCIA DI CONFIGURAZIONE...
}//GEN-LAST:event_configure_itemActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// AGGIUNGI UN FILE ALLA LISTA DI QUELLI IN POSSESSO...
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// RIMUOVI UN FILE DALLA LISTA DI QUELLI IN POSSESSO...
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable On_connection_table;
    private javax.swing.JTable Sn_connection_table;
    private javax.swing.JMenuItem add_on_item;
    private javax.swing.JMenuItem add_sn_item;
    private javax.swing.JMenuItem close_item;
    private javax.swing.JMenuItem configure_item;
    private javax.swing.JMenuItem connect_item;
    private javax.swing.JMenuItem disconnect_item;
    private javax.swing.JMenu edit_menu;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenuItem help_item;
    private javax.swing.JMenuItem italian_help_item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField my_address_tf;
    private javax.swing.JMenu question_menu;
    private javax.swing.JMenuItem remove_on_item;
    private javax.swing.JMenuItem remove_sn_item;
    // End of variables declaration//GEN-END:variables

}
